# fly.toml app configuration file generated for biomedical-detection-thrumming-butterfly-98 on 2025-04-23T19:50:26+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'biomedical-detection'
primary_region = 'iad'

[build]
  dockerfile = './Dockerfile'

[env]
  PORT = '8000'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

[[services]]
  protocol = 'tcp'
  internal_port = 8000

  [[services.ports]]
    port = 80
    handlers = ['http']

  [[services.ports]]
    port = 443
    handlers = ['tls', 'http']

[[vm]]
  memory = '2gb'  # Increased memory to 2GB
  cpu_kind = 'shared'
  cpus = 1
